---
version: "3.8"

services:
  my-service-production:
    container_name: my-service-production
    env_file:
      - .env
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512m"
        reservations:
          cpus: "0.25"
          memory: "256m"

volumes:
  node_modules:
